"use client";

import { useState, useEffect } from "react";
import { Mic, FastForward, Send, BarChart2, Smartphone, QrCode } from "lucide-react";
import { BarChart, Bar, XAxis, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { motion } from "framer-motion";
import { QRCodeSVG } from "qrcode.react";

// Mock Data (Questions generated by AI later)

const MOCK_QUESTIONS = [
    { id: 1, text: "AIは教育の質を向上させると思いますか？", options: ["はい", "いいえ", "わからない"] },
    { id: 2, text: "最も懸念される点は何ですか？", options: ["プライバシー", "依存度", "コスト", "公平性"] },
    { id: 3, text: "教師の役割はどう変わるべきですか？", options: ["ファシリテーター", "メンター", "変わらない"] }
];

export default function OrganizerDashboard() {
    const [transcription, setTranscription] = useState("");
    const [questions, setQuestions] = useState<typeof MOCK_QUESTIONS>([]);
    const [activeQuestionId, setActiveQuestionId] = useState<number | null>(null);
    const [results, setResults] = useState<{ name: string, value: number, color: string }[]>([]);
    const [showQRCode, setShowQRCode] = useState(false);
    const [participantUrl, setParticipantUrl] = useState("");

    const [apiKey, setApiKey] = useState("");
    const [isGenerating, setIsGenerating] = useState(false);

    // Set Participant URL on mount
    useEffect(() => {
        setParticipantUrl(`${window.location.origin}/participant`);
    }, []);

    // Mock recording effect removed

    // Poll for Results
    useEffect(() => {
        const fetchResults = async () => {
            try {
                const res = await fetch('/api/session');
                const data = await res.json();
                if (data.answers) {
                    const formattedResults = Object.keys(data.answers).map((key, index) => ({
                        name: key,
                        value: data.answers[key],
                        color: ["#f97316", "#3abff8", "#9ca3af", "#4ade80"][index % 4]
                    }));
                    setResults(formattedResults);
                }
            } catch (error) {
                console.error("Failed to fetch results", error);
            }
        };

        const interval = setInterval(fetchResults, 2000); // Poll every 2 seconds
        return () => clearInterval(interval);
    }, []);

    const handleGenerateQuestions = async () => {
        if (!apiKey) {
            alert("Gemini API Keyを入力してください");
            return;
        }
        setIsGenerating(true);
        try {
            const context = transcription;
            const res = await fetch('/api/ai/generate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ apiKey, context }),
            });
            const data = await res.json();
            if (data.questions) {
                setQuestions(data.questions);
            } else {
                console.error("Failed to generate questions", data);
                alert(`問いの生成に失敗しました: ${data.error || '不明なエラー'}`);
            }
        } catch (error: any) {
            console.error("Error calling AI API", error);
            alert(`エラーが発生しました: ${error.message}`);
        } finally {
            setIsGenerating(false);
        }
    };

    const handleDistribute = async (question: typeof MOCK_QUESTIONS[0]) => {
        setActiveQuestionId(question.id);
        try {
            await fetch('/api/session', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ type: 'distribute', question }),
            });
        } catch (error) {
            console.error("Failed to distribute question", error);
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 p-6 font-sans text-slate-800">
            <header className="mb-8 flex items-center justify-between">
                <h1 className="text-3xl font-bold tracking-tight text-slate-900">
                    <span className="text-primary">Active</span> Learning 運営ダッシュボード
                </h1>
                <div className="flex items-center gap-4">
                    <button
                        onClick={() => setShowQRCode(!showQRCode)}
                        className="flex items-center gap-2 rounded-lg bg-white border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
                    >
                        <QrCode size={18} />
                        参加者QRを表示
                    </button>
                </div>
            </header>

            {/* QR Code Modal/Overlay */}
            {showQRCode && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm" onClick={() => setShowQRCode(false)}>
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="bg-white p-8 rounded-2xl shadow-2xl text-center max-w-sm w-full"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <h2 className="text-xl font-bold mb-4 text-slate-800">参加者用QRコード</h2>
                        <div className="bg-white p-4 rounded-xl shadow-inner border border-gray-100 inline-block mb-4">
                            <QRCodeSVG value={participantUrl} size={200} />
                        </div>
                        <p className="text-sm text-gray-500 mb-6 break-all">{participantUrl}</p>
                        <div className="flex justify-center gap-2 text-xs text-gray-400">
                            <Smartphone size={16} />
                            <span>スマホで読み取ってください</span>
                        </div>
                        <button
                            onClick={() => setShowQRCode(false)}
                            className="mt-6 w-full py-2 rounded-lg bg-gray-100 text-gray-600 hover:bg-gray-200 font-medium"
                        >
                            閉じる
                        </button>
                    </motion.div>
                </div>
            )}

            <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
                {/* Transcription Area (Real-time Speech) */}
                <section className="col-span-1 rounded-2xl bg-white p-6 shadow-sm border border-gray-100 lg:col-span-2">
                    <h2 className="mb-4 text-xl font-semibold flex items-center gap-2 text-slate-700">
                        <Mic className="text-secondary" size={20} /> リアルタイム文字起こし
                    </h2>
                    <textarea
                        className="h-64 w-full rounded-lg border border-gray-200 bg-gray-50 p-4 font-mono text-sm leading-relaxed text-gray-800 focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none resize-none"
                        placeholder="ここに議論の内容を入力してください..."
                        value={transcription}
                        onChange={(e) => setTranscription(e.target.value)}
                    />
                </section>

                {/* AI Control Panel */}
                <section className="col-span-1 flex flex-col gap-6">
                    <div className="rounded-2xl bg-white p-6 shadow-sm border border-gray-100">
                        <h2 className="mb-4 text-xl font-semibold text-slate-700 flex items-center gap-2">
                            <FastForward className="text-primary" size={20} />
                            AI アクション
                        </h2>

                        <div className="mb-4">
                            <input
                                type="password"
                                placeholder="Gemini API Key"
                                value={apiKey}
                                onChange={(e) => setApiKey(e.target.value)}
                                className="w-full rounded-lg border border-gray-300 p-2 text-sm"
                            />
                        </div>

                        <button
                            onClick={handleGenerateQuestions}
                            disabled={transcription.length === 0 || isGenerating}
                            className="w-full rounded-xl bg-gradient-to-r from-orange-400 to-orange-600 px-4 py-3 text-white shadow-lg shadow-orange-200 transition-all hover:scale-[1.02] hover:shadow-xl disabled:opacity-50 disabled:hover:scale-100"
                        >
                            {isGenerating ? "生成中..." : "問いを生成する"}
                        </button>
                    </div>

                    {/* Real-time Results Preview */}
                    <div className="flex-1 rounded-2xl bg-white p-6 shadow-sm border border-gray-100">
                        <h2 className="mb-4 text-xl font-semibold text-slate-700 flex items-center gap-2">
                            <BarChart2 className="text-secondary" size={20} />
                            リアルタイム集計
                        </h2>
                        {results.length > 0 ? (
                            <div className="h-48 w-full">
                                <ResponsiveContainer width="100%" height="100%">
                                    <BarChart data={results}>
                                        <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                                        <Tooltip cursor={{ fill: 'transparent' }} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                                        <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                                            {results.map((entry, index) => (
                                                <Cell key={`cell-${index}`} fill={entry.color} />
                                            ))}
                                        </Bar>
                                    </BarChart>
                                </ResponsiveContainer>
                            </div>
                        ) : (
                            <div className="flex h-48 items-center justify-center rounded-lg border-2 border-dashed border-gray-200 bg-gray-50 text-gray-400">
                                {activeQuestionId ? "回答待ち..." : "アクティブな問いがありません"}
                            </div>
                        )}
                    </div>
                </section>

                {/* Generated Questions List using full width if plenty generated */}
                {questions.length > 0 && (
                    <section className="col-span-1 lg:col-span-3 rounded-2xl bg-white p-6 shadow-sm border border-gray-100">
                        <h2 className="mb-4 text-xl font-semibold text-slate-700">生成された問い</h2>
                        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                            {questions.map((q) => (
                                <motion.div
                                    key={q.id}
                                    initial={{ opacity: 0, scale: 0.95 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    className={`relative rounded-xl border p-5 transition-all ${activeQuestionId === q.id ? "border-primary bg-orange-50 ring-2 ring-primary/20" : "border-gray-200 bg-white hover:border-gray-300"}`}
                                >
                                    <h3 className="mb-3 font-medium text-gray-800">{q.text}</h3>
                                    <div className="mb-4 flex flex-wrap gap-2">
                                        {q.options.map((opt, i) => (
                                            <span key={i} className="rounded-md bg-gray-100 px-2 py-1 text-xs text-gray-600">{opt}</span>
                                        ))}
                                    </div>
                                    <button
                                        onClick={() => handleDistribute(q)}
                                        className={`flex w-full items-center justify-center gap-2 rounded-lg py-2 text-sm font-medium transition-colors ${activeQuestionId === q.id ? "bg-primary text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}
                                    >
                                        <Send size={16} />
                                        {activeQuestionId === q.id ? "配信中" : "配信する"}
                                    </button>
                                </motion.div>
                            ))}
                        </div>
                    </section>
                )}
            </div>
        </div>
    );
}
